### ISSUE TITLE
Requirements installation failed

### ISSUE THREAD

**Issue by SAppleton** [rh-aiservices-bu/mnist-tensorflow-model#1]
I tried running this on my OCP demo account and the requirements failed to install.
I had some success changing the versions for tensorflow to 2.12 and keras to 2.12 but it still failed
Can somebody re-check this as it these reqs are now 2 years old 

~~~
h5py==2.10.0
keras==2.12.*
tensorflow==2.12.*
requests
Pillow
~~~

**Comment by SAppleton** [comment]
I was using https://rhods-dashboard-redhat-ods-applications.apps.sandbox-m4.g2pi.p1.openshiftapps.com/notebookController

**Comment by adelton** [comment]
I see the failure as well, specifically:
```
(app-root) (app-root) pip install -r requirements.txt
Collecting h5py==2.10.0 (from -r requirements.txt (line 1))
  Downloading h5py-2.10.0.tar.gz (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.1/301.1 kB 19.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting keras==2.4.* (from -r requirements.txt (line 2))
  Downloading Keras-2.4.3-py2.py3-none-any.whl (36 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.* (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.14.0rc0, 2.14.0rc1)
ERROR: No matching distribution found for tensorflow==2.4.*

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
```

Updating to `2.12.*` changes the output to
```
[...]
Requirement already satisfied: oauthlib>=3.0.0 in /opt/app-root/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow==2.12.*->-r requirements.txt (line 3)) (3.2.2)
Building wheels for collected packages: h5py, jax
  Building wheel for h5py (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      /opt/app-root/lib64/python3.9/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/__init__.py -> build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/h5py_warnings.py -> build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/highlevel.py -> build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/ipy_completer.py -> build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/version.py -> build/lib.linux-x86_64-cpython-39/h5py
      creating build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/base.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/compat.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/dims.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/files.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/filters.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/group.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/selections.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/vds.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      creating build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/__init__.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/common.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_attribute_create.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_attrs.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_attrs_data.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_base.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_completions.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dataset.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_datatype.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_deprecation.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dimension_scales.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dtype.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_file.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_file2.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_file_image.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_filters.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_group.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5f.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5p.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5pl.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5t.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_objects.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_selections.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_slicing.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_threads.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      creating build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      copying h5py/tests/test_vds/__init__.py -> build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      running build_ext
      Loading library to get version: libhdf5.so
      error: libhdf5.so: cannot open shared object file: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
  Running setup.py clean for h5py
  Building wheel for jax (pyproject.toml) ... done
  Created wheel for jax: filename=jax-0.4.14-py3-none-any.whl size=1535361 sha256=4e76505d8f2998f43c3470399d1965d150f453b58b2e770f47fd580f65b7bf24
  Stored in directory: /tmp/pip-ephem-wheel-cache-xd4yh7zi/wheels/b2/6a/ae/ac83488c58ba1ef1c6720d8b9b685994249f7ed7f1a7294f00
Successfully built jax
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
```

Adding the `--use-pep517` option changes this to
```
Requirement already satisfied: oauthlib>=3.0.0 in /opt/app-root/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow==2.12.*->-r requirements.txt (line 3)) (3.2.2)
Building wheels for collected packages: h5py, jax
  Building wheel for h5py (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for h5py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [109 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/__init__.py -> build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/h5py_warnings.py -> build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/highlevel.py -> build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/ipy_completer.py -> build/lib.linux-x86_64-cpython-39/h5py
      copying h5py/version.py -> build/lib.linux-x86_64-cpython-39/h5py
      creating build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/base.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/compat.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/dims.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/files.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/filters.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/group.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/selections.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      copying h5py/_hl/vds.py -> build/lib.linux-x86_64-cpython-39/h5py/_hl
      creating build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/__init__.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/common.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_attribute_create.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_attrs.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_attrs_data.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_base.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_completions.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dataset.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_datatype.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_deprecation.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dimension_scales.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_dtype.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_file.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_file2.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_file_image.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_filters.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_group.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5f.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5p.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5pl.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_h5t.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_objects.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_selections.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_slicing.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      copying h5py/tests/test_threads.py -> build/lib.linux-x86_64-cpython-39/h5py/tests
      creating build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      copying h5py/tests/test_vds/__init__.py -> build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-x86_64-cpython-39/h5py/tests/test_vds
      running build_ext
      Traceback (most recent call last):
        File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 140, in <module>
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-561kbpev/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-qrdlvbtz/h5py_ecb1f83609c4436e982e42badf100edc/setup_build.py", line 161, in run
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
  Building wheel for jax (pyproject.toml) ... done
  Created wheel for jax: filename=jax-0.4.14-py3-none-any.whl size=1535361 sha256=f2a6941dd58dad9cee7519681fe787d52372e2f92cfc08ae7a225d616f0e515e
  Stored in directory: /tmp/pip-ephem-wheel-cache-5els5g3p/wheels/b2/6a/ae/ac83488c58ba1ef1c6720d8b9b685994249f7ed7f1a7294f00
Successfully built jax
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
```

When following https://developers.redhat.com/learning/learn:openshift-data-science:how-create-tensorflow-model/resource/resources:explore-mnist-dataset and the DevSandbox, I get unsubscribed RHEL 9.2, so it's not even possible to install the possibly needed `*-devel` packages.

**Comment by adelton** [comment]
In a Fedora 38 container, running
```
dnf install python3-h5py
```
and updating the `requirements.py` to say
```
h5py==3.7.0
```
makes the `pip install` call pass.
